sap.ui.define([], function () {
  'use strict';

  return {
    COLORS: ['#7BB4EB', '#81DAEA', '#A9F482', '#FFE479', '#FFB7AF', '#FFAC4B', '#D484F2', '#A684F2', '#9090FF', '#ACB3FF'],
    CHART_TYPE: [
      {
        Headty: 'A',
        Target: 'A01',
        Chart: 'none',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Cnt01'] }, //
          { prop: 'Cnt02', path: [0, 'Cnt02'] },
          { prop: 'Cnt03', path: [0, 'Cnt03'] },
          { prop: 'Cnt40', path: [1, 'Cnt01'] },
          { prop: 'Cnt41', path: [1, 'Cnt02'] },
          { prop: 'Cnt42', path: [1, 'Cnt03'] },
          { prop: 'Cnt50', path: [2, 'Cnt01'] },
          { prop: 'Cnt51', path: [2, 'Cnt02'] },
          { prop: 'Cnt52', path: [2, 'Cnt03'] },
          { prop: 'Cnt60', path: [3, 'Cnt01'] },
          { prop: 'Cnt61', path: [3, 'Cnt02'] },
          { prop: 'Cnt62', path: [3, 'Cnt03'] },
          { prop: 'Cnt70', path: [4, 'Cnt01'] },
          { prop: 'Cnt71', path: [4, 'Cnt02'] },
          { prop: 'Cnt72', path: [4, 'Cnt03'] },
        ],
      },
      {
        Headty: 'B',
        Target: 'A05',
        Chart: 'column2d',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Rte01'] }, //
        ],
      },
      {
        Headty: 'C',
        Target: 'A09',
        Chart: 'column2d',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Rte01'] }, //
        ],
      },
      {
        Headty: 'D',
        Target: 'A02',
        Chart: 'hled',
        Fields: [
          { prop: 'Title01', path: [0, 'Ttltxt'] }, //
          { prop: 'Title10', path: [1, 'Ttltxt'] },
          { prop: 'Title20', path: [2, 'Ttltxt'] },
          { prop: 'Cnt01', path: [0, 'Cnt01'] },
          { prop: 'Cnt02', path: [0, 'Rte01'] },
          { prop: 'Cnt11', path: [1, 'Rte01'] },
          { prop: 'Cnt12', path: [1, 'Cnt01'] },
          { prop: 'Cnt21', path: [2, 'Rte01'] },
          { prop: 'Cnt22', path: [2, 'Cnt01'] },
        ],
        RangeCount: 3,
        Limit: '100',
        UsedProp: 'Rte01',
      },
      {
        Headty: 'E',
        Target: 'A06',
        Chart: 'hled',
        Fields: [
          { prop: 'Cnt11', path: [0, 'Rte01'] },
          { prop: 'Cnt12', path: [0, 'Cnt01'] },
          { prop: 'Cnt21', path: [1, 'Rte01'] },
          { prop: 'Cnt22', path: [1, 'Cnt01'] },
        ],
        RangeCount: 2,
        Limit: '',
        UsedProp: 'Cnt01',
      },
      { Headty: 'F', Target: 'A10', Chart: 'bar2d' },
      { Headty: 'G', Target: 'A03', Chart: 'doughnut2d' },
      { Headty: 'H', Target: 'A07', Chart: 'doughnut2d' },
      { Headty: 'I', Target: 'A04', Chart: 'doughnut2d' },
      { Headty: 'J', Target: 'A08', Chart: 'doughnut2d' },
      { Headty: 'K', Target: 'A11', Chart: 'mscolumn2d' },
    ],
    CHART: {
      A02: {
        id: 'employee-a02-chart',
        type: 'hled',
        data: {
          chart: {
            animation: '0',
            chartbottommargin: '5',
            ledGap: '0',
            lowerLimit: '0',
            minorTMNumber: '0',
            upperLimit: '100',
            tickMarkDistance: '1',
            majorTMColor: '#ededed',
            theme: 'ocean',
            showvalue: '0',
            showShadow: '0',
            showGaugeBorder: '0',
            showToolTip: '0',
          },
          colorrange: {
            color: [
              {
                minvalue: '0',
                maxvalue: '22',
                code: '#7BB4EB',
              },
              {
                minvalue: '23',
                maxvalue: '25',
                code: '#FC564F',
              },
              {
                minvalue: '26',
                maxvalue: '100',
                code: '#ededed',
              },
            ],
          },
          value: '100',
        },
      },
      A03: {
        id: 'employee-a03-chart',
        type: 'doughnut2d',
        data: {
          chart: {
            showpercentvalues: '1',
            aligncaptionwithcanvas: '0',
            captionpadding: '0',
            decimals: '1',
            theme: 'ocean',
            showLabels: '0',
            labelDistance: '-25',
            startingAngle: '330',
            chartTopMargin: 0,
            chartTopRight: 0,
            chartTopBottom: 0,
            chartTopLeft: 0,
            paletteColors: '#7BB4EB,#81DAEA,#77D561,#FFE479,#FC564F',
          },
          data: [
            {
              label: '일반직',
              value: '292',
            },
            {
              label: '임원',
              value: '8',
            },
            {
              label: '계약직',
              value: '4',
            },
            {
              label: '별정직',
              value: '3',
            },
            {
              label: '파견직',
              value: '1',
            },
          ],
        },
      },
      A04: {
        id: 'employee-a04-chart',
        type: 'doughnut2d',
        data: {
          chart: {
            showpercentvalues: '1',
            aligncaptionwithcanvas: '0',
            captionpadding: '0',
            decimals: '1',
            theme: 'ocean',
            showLabels: '0',
            labelDistance: '-25',
            startingAngle: '330',
            chartTopMargin: 0,
            chartTopRight: 0,
            chartTopBottom: 0,
            chartTopLeft: 0,
            paletteColors: '#7BB4EB,#81DAEA,#77D561',
          },
          data: [
            {
              label: '팀원',
              value: '274',
            },
            {
              label: '팀장',
              value: '26',
            },
            {
              label: '임원',
              value: '8',
            },
          ],
        },
      },
      A05: {
        id: 'employee-a05-chart',
        type: 'column2d',
        data: {
          chart: {
            showValues: 1,
            rotateValues: 0,
            placeValuesInside: 0,
            yAxisValueFontSize: 9,
            // yAxisMaxValue: 300,
            numDivLines: 3,
            divLineDashed: 0,
            divLineColor: '#eeeeee',
            maxColWidth: 23,
            theme: 'ocean',
            bgColor: 'transparent',
            valueFontSize: 9,
            valueFontColor: '#000000',
            valueBgColor: '#ffffff',
            showPlotBorder: 1,
            plotBorderThickness: 3,
            plotBorderColor: '#ffffff',
            chartBottomMargin: 0,
            drawCustomLegendIcon: 1,
          },
          data: [
            {
              label: '0-10',
              value: '173',
              color: '#7BB4EB',
            },
            {
              label: '10-20',
              value: '98',
              color: '#7BB4EB',
            },
            {
              label: '20-30',
              value: '42',
              color: '#7BB4EB',
            },
            {
              label: '30-40',
              value: '12',
              color: '#7BB4EB',
            },
          ],
        },
      },
      A06: {
        id: 'employee-a06-chart',
        type: 'hled',
        data: {
          chart: {
            animation: '0',
            chartbottommargin: '5',
            ledGap: '0',
            lowerLimit: '0',
            minorTMNumber: '0',
            upperLimit: '311',
            tickMarkDistance: '1',
            majorTMColor: '#ededed',
            theme: 'ocean',
            showvalue: '0',
            showShadow: '0',
            showGaugeBorder: '0',
            showToolTip: '0',
          },
          colorrange: {
            color: [
              {
                minvalue: '0',
                maxvalue: '287',
                code: '#7BB4EB',
              },
              {
                minvalue: '288',
                maxvalue: '311',
                code: '#FC564F',
              },
            ],
          },
          value: '311',
        },
      },
      A07: {
        id: 'employee-a07-chart',
        type: 'doughnut2d',
        data: {
          chart: {
            showpercentvalues: '1',
            aligncaptionwithcanvas: '0',
            captionpadding: '0',
            decimals: '1',
            theme: 'ocean',
            showLabels: '0',
            labelDistance: '-25',
            startingAngle: '330',
            chartTopMargin: 0,
            chartTopRight: 0,
            chartTopBottom: 0,
            chartTopLeft: 0,
            paletteColors: '#7BB4EB,#81DAEA,#77D561,#FFE479',
          },
          data: [
            {
              label: '안전',
              value: '117',
            },
            {
              label: '고객서비스',
              value: '64',
            },
            {
              label: '지원',
              value: '53',
            },
            {
              label: '기술',
              value: '38',
            },
          ],
        },
      },
      A08: {
        id: 'employee-a08-chart',
        type: 'doughnut2d',
        data: {
          chart: {
            showpercentvalues: '1',
            aligncaptionwithcanvas: '0',
            captionpadding: '0',
            decimals: '1',
            theme: 'ocean',
            showLabels: '0',
            labelDistance: '-25',
            startingAngle: '330',
            chartTopMargin: 0,
            chartTopRight: 0,
            chartTopBottom: 0,
            chartTopLeft: 0,
            paletteColors: '#7BB4EB,#81DAEA,#77D561,#FFE479',
          },
          data: [
            {
              label: '안전',
              value: '117',
            },
            {
              label: '고객서비스',
              value: '64',
            },
            {
              label: '지원',
              value: '53',
            },
            {
              label: '기술',
              value: '38',
            },
          ],
        },
      },
      A09: {
        id: 'employee-a09-chart',
        type: 'column2d',
        data: {
          chart: {
            showValues: 1,
            rotateValues: 0,
            placeValuesInside: 0,
            yAxisValueFontSize: 9,
            // yAxisMaxValue: 300,
            numDivLines: 3,
            divLineDashed: 0,
            divLineColor: '#eeeeee',
            maxColWidth: 23,
            theme: 'ocean',
            bgColor: 'transparent',
            valueFontSize: 9,
            valueFontColor: '#000000',
            valueBgColor: '#ffffff',
            showPlotBorder: 1,
            plotBorderThickness: 3,
            plotBorderColor: '#ffffff',
            chartBottomMargin: 0,
            drawCustomLegendIcon: 1,
          },
          data: [
            {
              label: '20-30',
              value: '100',
              color: '#7BB4EB',
            },
            {
              label: '30-40',
              value: '178',
              color: '#7BB4EB',
            },
            {
              label: '40-50',
              value: '88',
              color: '#7BB4EB',
            },
            {
              label: '50-60',
              value: '39',
              color: '#7BB4EB',
            },
            {
              label: '60이상',
              value: '25',
              color: '#7BB4EB',
            },
          ],
        },
      },
      A10: {
        id: 'employee-a10-chart',
        type: 'bar2d',
        data: {
          chart: {
            showValues: 1,
            rotateValues: 0,
            placeValuesInside: 0,
            yAxisValueFontSize: 9,
            // yAxisMaxValue: 200,
            numDivLines: 3,
            divLineDashed: 0,
            divLineColor: '#eeeeee',
            maxColWidth: 23,
            theme: 'ocean',
            bgColor: 'transparent',
            valueFontSize: 9,
            valueFontColor: '#000000',
            valueBgColor: '#ffffff',
            showPlotBorder: 1,
            plotBorderThickness: 3,
            plotBorderColor: '#ffffff',
            chartBottomMargin: 0,
            drawCustomLegendIcon: 1,
          },
          data: [
            {
              label: '경영진단팀',
              value: '4',
              color: '#7BB4EB',
            },
            {
              label: '기획재경부문',
              value: '23',
              color: '#7BB4EB',
            },
            {
              label: '경영지원부문',
              value: '29',
              color: '#7BB4EB',
            },
            {
              label: '안전부문',
              value: '170',
              color: '#7BB4EB',
            },
            {
              label: '고객서비스부문',
              value: '76',
              color: '#7BB4EB',
            },
          ],
        },
      },
      A11: {
        id: 'employee-a11-chart',
        type: 'mscolumn2d',
        data: {
          chart: {
            animation: 0,
            showValues: 1,
            rotateValues: 0,
            placeValuesInside: 0,
            yAxisValueFontSize: 9,
            // yAxisMaxValue: 230,
            numDivLines: 3,
            divLineDashed: 0,
            divLineColor: '#eeeeee',
            maxColWidth: 23,
            theme: 'ocean',
            bgColor: 'transparent',
            valueFontSize: 9,
            valueFontColor: '#000000',
            valueBgColor: '#ffffff',
            showPlotBorder: 1,
            plotBorderThickness: 3,
            plotBorderColor: '#ffffff',
            chartBottomMargin: 0,
            drawCustomLegendIcon: 1,
          },
          categories: [
            {
              category: [
                { label: '2012' }, //
                { label: '2013' },
                { label: '2014' },
                { label: '2015' },
                { label: '2016' },
                { label: '2017' },
                { label: '2018' },
                { label: '2019' },
                { label: '2020' },
                { label: '2021' },
              ],
            },
          ],
          dataset: [
            {
              seriesname: '팀원',
              color: '#7BB4EB',
              data: [
                { value: 38.2 }, //
                { value: 42.5 },
                { value: 39.9 },
                { value: 38.8 },
                { value: 40.7 },
                { value: 49.2 },
                { value: 36.3 },
                { value: 36.5 },
                { value: 41.4 },
                { value: 37.8 },
              ],
            },
            {
              seriesname: '팀장',
              color: '#FFE479',
              data: [
                { value: 10.1 }, //
                { value: 10.8 },
                { value: 10.9 },
                { value: 11.2 },
                { value: 10.3 },
                { value: 11.7 },
                { value: 13.7 },
                { value: 11.6 },
                { value: 10.6 },
                { value: 10.5 },
              ],
            },
          ],
        },
      },
    },
  };
});
