sap.ui.define([], function () {
  'use strict';

  return {
    COLORS: ['#7BB4EB', '#81DAEA', '#A9F482', '#FFE479', '#FFB7AF', '#FFAC4B', '#D484F2', '#A684F2', '#9090FF', '#ACB3FF'],
    CHART_TYPE: [
      {
        Headty: 'A',
        Target: 'A01',
        Chart: 'cylinder',
        ChartWidth: '110px',
        DetailEntity: 'TimeOverviewDetail1',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Cnt01'] }, //
          { prop: 'Cnt02', path: [0, 'Cnt02'] },
          { prop: 'Cnt03', path: [0, 'Cnt03'] },
          { prop: 'Cnt04', path: [0, 'Cnt04'] },
          { prop: 'Cnt05', path: [0, 'Cnt05'] },
          { prop: 'Cnt06', path: [0, 'Cnt06'] },
          { prop: 'Cnt07', path: [0, 'Cnt07'] },
          { prop: 'Cnt08', path: [0, 'Cnt08'] },
          { prop: 'Cnt01C', path: [0, 'Cod01'] },
          { prop: 'Cnt02C', path: [0, 'Cod02'] },
          { prop: 'Cnt03C', path: [0, 'Cod03'] },
          { prop: 'Cnt04C', path: [0, 'Cod04'] },
          { prop: 'Cnt05C', path: [0, 'Cod05'] },
          { prop: 'Cnt06C', path: [0, 'Cod06'] },
          { prop: 'Cnt07C', path: [0, 'Cod07'] },
          { prop: 'Cnt08C', path: [0, 'Cod08'] },
        ],
      },
      {
        Headty: 'B',
        Target: 'A02',
        Chart: 'column2d',
        DetailEntity: 'TimeOverviewDetail3',
        Fields: [
          { prop: 'Rte01', path: [0, 'Rte01'] }, //
          { prop: 'Rte02', path: [0, 'Rte02'] },
        ],
      },
      {
        Headty: 'C',
        Target: 'A03',
        Chart: 'column2d',
        DetailEntity: 'TimeOverviewDetail3',
        Fields: [
          { prop: 'Rte01', path: [0, 'Rte01'] }, //
          { prop: 'Rte02', path: [0, 'Rte02'] },
        ],
      },
      {
        Headty: 'D',
        Target: 'A04',
        Chart: 'none',
        DetailEntity: 'TimeOverviewDetail2',
        Fields: [
          { prop: 'Rte01', path: [0, 'Rte01'] }, //
          { prop: 'Rte02', path: [0, 'Rte02'] },
          { prop: 'Cnt01', path: [0, 'Cnt01'] },
          { prop: 'Cnt02', path: [0, 'Cnt02'] },
          { prop: 'Cnt03', path: [0, 'Cnt03'] },
          { prop: 'Cnt04', path: [0, 'Cnt04'] },
          { prop: 'Cnt01C', path: [0, 'Cod01'] },
          { prop: 'Cnt02C', path: [0, 'Cod02'] },
          { prop: 'Cnt03C', path: [0, 'Cod03'] },
          { prop: 'Cnt04C', path: [0, 'Cod04'] },
        ],
      },
      { Headty: 'E', Target: 'A05', Chart: 'bar2d', DetailEntity: 'TimeOverviewDetail2' },
      { Headty: 'F', Target: 'A06', Chart: 'bar2d', DetailEntity: 'TimeOverviewDetail2' },
      { Headty: 'G', Target: 'A07', Chart: 'mscombi2d', DetailEntity: 'TimeOverviewDetail2' },
      {
        Headty: 'H',
        Target: 'A08',
        Chart: 'bar2d',
        DetailEntity: 'TimeOverviewDetail3',
        Fields: [
          { prop: 'Rte02', path: [0, 'Rte02'] }, //
        ],
      },
      {
        Headty: 'I',
        Target: 'A09',
        Chart: 'bar2d',
        DetailEntity: 'TimeOverviewDetail3',
        Fields: [
          { prop: 'Rte02', path: [0, 'Rte02'] }, //
        ],
      },
      { Headty: 'J', Target: 'A10', Chart: 'mscolumn2d', DetailEntity: 'TimeOverviewDetail3' },
    ],
    CHART_OPTIONS: {
      cylinder: {
        chart: {
          caption: '', // 출근율
          lowerlimit: '0',
          upperlimit: '100',
          lowerlimitdisplay: '0%',
          upperlimitdisplay: '100%',
          numbersuffix: '%',
          cylfillcolor: '#5d62b5',
          cylfillhoveralpha: '85',
          animation: 1,
          refreshInstantly: 1,
          theme: 'ocean',
          chartTopMargin: 0,
          chartBottomMargin: 0,
          cylFillColor: '#30c4ee',
          cylYScale: 10,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plottooltext: '출근율 $dataValue',
        },
        value: 10,
      },
      column2d: {
        chart: {
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          xAxisNameFontSize: 9,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 18,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          // chartTopMargin: 0,
          chartRightMargin: 0,
          chartBottomMargin: 0,
          chartLeftMargin: 1,
          drawCustomLegendIcon: 1,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$label</th><td>$value</td></tr></table></div>",
        },
        data: [],
      },
      bar2d: {
        chart: {
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          xAxisNameFontSize: 9,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 18,
          theme: 'ocean',
          bgColor: 'transparent',
          valueBgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          chartTopMargin: 0,
          chartRightMargin: 0,
          chartBottomMargin: 0,
          chartLeftMargin: 0,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$label</th><td>$value</td></tr></table></div>",
        },
        data: [],
      },
      mscolumn2d: {
        chart: {
          animation: 0,
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          // yAxisMaxValue: 230,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 23,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          legendIconSides: 0,
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          chartBottomMargin: 0,
          drawCustomLegendIcon: 1,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        },
        categories: [{ category: [] }],
        dataset: [],
      },
      mscombi2d: {
        chart: {
          showSum: 1,
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 25,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: 'transparent',
          showPlotBorder: 0,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          chartTopMargin: 4,
          chartRightMargin: 0,
          chartBottomMargin: 0,
          chartLeftMargin: 0,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        },
        categories: [],
        dataset: [],
      },
    },
  };
});
