sap.ui.define([], function () {
  'use strict';

  return {
    COLORS: ['#7BB4EB', '#81DAEA', '#A9F482', '#FFE479', '#FFB7AF', '#FFAC4B', '#D484F2', '#A684F2', '#9090FF', '#ACB3FF'],
    CHART_TYPE: [
      {
        Headty: 'A',
        Target: 'A01',
        Chart: 'cylinder',
        ChartWidth: '110px',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Cnt01'] }, //
          { prop: 'Cnt02', path: [0, 'Cnt02'] },
          { prop: 'Cnt03', path: [0, 'Cnt03'] },
          { prop: 'Cnt04', path: [0, 'Cnt03'] },
          { prop: 'Cnt05', path: [0, 'Cnt03'] },
          { prop: 'Cnt06', path: [0, 'Cnt03'] },
          { prop: 'Cnt01C', path: [0, 'Cod01'] },
          { prop: 'Cnt02C', path: [0, 'Cod02'] },
          { prop: 'Cnt03C', path: [0, 'Cod03'] },
          { prop: 'Cnt04C', path: [0, 'Cod03'] },
          { prop: 'Cnt05C', path: [0, 'Cod03'] },
          { prop: 'Cnt06C', path: [0, 'Cod03'] },
        ],
      },
      { Headty: 'B', Target: 'A02', Chart: 'column2d' },
      { Headty: 'E', Target: 'A03', Chart: 'column2d' },
      { Headty: 'C', Target: 'A04', Chart: 'none' },
      { Headty: 'D', Target: 'A05', Chart: 'bar2d' },
      { Headty: 'D', Target: 'A06', Chart: 'bar2d' },
      { Headty: 'G', Target: 'A07', Chart: 'mscombi2d' },
      { Headty: 'D', Target: 'A08', Chart: 'bar2d' },
      { Headty: 'D', Target: 'A09', Chart: 'bar2d' },
      { Headty: 'G', Target: 'A10', Chart: 'mscolumn2d' },
    ],
    CHART_OPTIONS: {
      cylinder: {
        chart: {
          caption: '', // 출근율
          lowerlimit: '0',
          upperlimit: '100',
          lowerlimitdisplay: '0%',
          upperlimitdisplay: '100%',
          numbersuffix: '%',
          cylfillcolor: '#5d62b5',
          cylfillhoveralpha: '85',
          animation: 1,
          refreshInstantly: 1,
          theme: 'ocean',
          chartTopMargin: 0,
          chartBottomMargin: 0,
          cylFillColor: '#30c4ee',
          cylYScale: 10,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plottooltext: '출근율 $dataValue',
        },
        value: 10,
      },
      column2d: {
        chart: {
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 23,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          chartBottomMargin: 0,
          drawCustomLegendIcon: 1,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$label</th><td>$value</td></tr></table></div>",
        },
        data: [],
      },
      bar2d: {
        chart: {
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          // yAxisMaxValue: 200,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 23,
          theme: 'ocean',
          bgColor: 'transparent',
          valueBgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          chartBottomMargin: 2,
          drawCustomLegendIcon: 1,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$label</th><td>$value</td></tr></table></div>",
        },
        data: [],
      },
      mscolumn2d: {
        chart: {
          animation: 0,
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          yAxisValueFontSize: 9,
          // yAxisMaxValue: 230,
          numDivLines: 3,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 23,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: '#ffffff',
          legendIconSides: 0,
          showPlotBorder: 1,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          chartBottomMargin: 0,
          drawCustomLegendIcon: 1,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        },
        categories: [{ category: [] }],
        dataset: [],
      },
      mscombi2d: {
        chart: {
          showSum: 1,
          showValues: 1,
          rotateValues: 0,
          placeValuesInside: 0,
          divLineDashed: 0,
          divLineColor: '#eeeeee',
          maxColWidth: 25,
          theme: 'ocean',
          bgColor: 'transparent',
          valueFontSize: 9,
          valueFontColor: '#000000',
          valueBgColor: 'transparent',
          showPlotBorder: 0,
          plotBorderThickness: 3,
          plotBorderColor: '#ffffff',
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          chartTopMargin: 4,
          chartRightMargin: 0,
          chartBottomMargin: 0,
          chartLeftMargin: 0,
          toolTipBgColor: '#ffffff',
          toolTipColor: '#222222',
          showToolTipShadow: 1,
          plotcolorintooltip: 1,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        },
        categories: [
          {
            category: [
              { label: 'Jan' }, //
              { label: 'Feb' },
              { label: 'Mar' },
              { label: 'Apr' },
              { label: 'May' },
              { label: 'Jun' },
              { label: 'Jul' },
              { label: 'Aug' },
              { label: 'Sep' },
              { label: 'Oct' },
              { label: 'Nov' },
              { label: 'Dec' },
            ],
          },
        ],
        dataset: [
          {
            seriesName: '당일',
            showValues: '1',
            color: '#7BB4EB',
            data: [
              { value: '10' }, //
              { value: '4' },
              { value: '7' },
              { value: '10' },
              { value: '6' },
              { value: '7' },
              { value: '10' },
              { value: '8' },
              { value: '7' },
              { value: '10' },
              { value: '9' },
              { value: '7' },
            ],
          },
          {
            seriesName: '누적',
            renderAs: 'line',
            color: '#FFAC4B',
            data: [
              { value: '10' }, //
              { value: '14' },
              { value: '21' },
              { value: '31' },
              { value: '37' },
              { value: '44' },
              { value: '54' },
              { value: '62' },
              { value: '69' },
              { value: '79' },
              { value: '88' },
              { value: '95' },
            ],
          },
        ],
      },
    },
  };
});
