sap.ui.define([], function () {
  'use strict';

  return {
    COLORS: ['#7BB4EB', '#81DAEA', '#A9F482', '#FFE479', '#FFB7AF', '#FFAC4B', '#D484F2', '#A684F2', '#9090FF', '#ACB3FF'],
    CHART_TYPE: [
      {
        Device: ['PC', 'Mobile'],
        Headty: 'A',
        Target: 'A01',
        Chart: 'none',
        EntityType: 'HeadCountOverview',
        Fields: [
          { prop: 'Cnt01', path: [0, 'Cnt01'] }, //
          { prop: 'Cnt02', path: [0, 'Cnt02'] },
          { prop: 'Cnt03', path: [0, 'Cnt03'] },
          { prop: 'Cnt01C', path: [0, 'Cod01'] },
          { prop: 'Cnt02C', path: [0, 'Cod02'] },
          { prop: 'Cnt03C', path: [0, 'Cod03'] },
          { prop: 'Cnt40', path: [1, 'Cnt01'] },
          { prop: 'Cnt41', path: [1, 'Cnt02'] },
          { prop: 'Cnt42', path: [1, 'Cnt03'] },
          { prop: 'Cnt40C', path: [1, 'Cod01'] },
          { prop: 'Cnt41C', path: [1, 'Cod02'] },
          { prop: 'Cnt42C', path: [1, 'Cod03'] },
          { prop: 'Cnt50', path: [2, 'Cnt01'] },
          { prop: 'Cnt51', path: [2, 'Cnt02'] },
          { prop: 'Cnt52', path: [2, 'Cnt03'] },
          { prop: 'Cnt50C', path: [2, 'Cod01'] },
          { prop: 'Cnt51C', path: [2, 'Cod02'] },
          { prop: 'Cnt52C', path: [2, 'Cod03'] },
          { prop: 'Cnt60', path: [3, 'Cnt01'] },
          { prop: 'Cnt61', path: [3, 'Cnt02'] },
          { prop: 'Cnt62', path: [3, 'Cnt03'] },
          { prop: 'Cnt60C', path: [3, 'Cod01'] },
          { prop: 'Cnt61C', path: [3, 'Cod02'] },
          { prop: 'Cnt62C', path: [3, 'Cod03'] },
          { prop: 'Cnt70', path: [4, 'Cnt01'] },
          { prop: 'Cnt71', path: [4, 'Cnt02'] },
          { prop: 'Cnt72', path: [4, 'Cnt03'] },
          { prop: 'Cnt70C', path: [4, 'Cod01'] },
          { prop: 'Cnt71C', path: [4, 'Cod02'] },
          { prop: 'Cnt72C', path: [4, 'Cod03'] },
        ],
      },
      { Device: ['PC', 'Mobile'], Headty: 'A', Target: 'A02', Chart: 'stackedcolumn2d-S', EntityType: 'HeadCountEntRet' },
      { Device: ['PC', 'Mobile'], Headty: 'B', Target: 'A04', Chart: 'stackedcolumn2d-S', EntityType: 'HeadCountEntRet' },
      { Device: ['PC', 'Mobile'], Headty: 'C', Target: 'A05', Chart: 'stackedcolumn2d-S', EntityType: 'HeadCountEntRet' },
      { Device: ['PC'], Headty: 'D', Target: 'A03', Chart: 'stackedcolumn2d', EntityType: 'HeadCountEntRet', minDisplayValue: 4 },
      { Device: ['Mobile'], Headty: 'D', Target: 'A03', Chart: 'scrollstackedcolumn2d', EntityType: 'HeadCountEntRet', minDisplayValue: 4 },
      { Device: ['PC'], Headty: 'E', Target: 'A06', Chart: 'msstackedcolumn2dlinedy', EntityType: 'HeadCountEntRet', minDisplayValue: 15 },
      { Device: ['Mobile'], Headty: 'E', Target: 'A06', Chart: 'scrollmsstackedcolumn2dlinedy', EntityType: 'HeadCountEntRet', minDisplayValue: 15 },
    ],
    CHART_OPTIONS: {
      'stackedcolumn2d-S': {
        chart: FusionCharts.curryChartOptions({
          showLegend: 0,
          xAxisLineThickness: 2,
          numDivLines: 0,
          divLineDashed: 0,
          divLineColor: '#ffffff',
          maxColWidth: 63,
          drawCustomLegendIcon: 1,
          chartTopMargin: 15,
          chartLeftMargin: 5,
          plotToolText: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        }),
        categories: [{ category: [] }],
        dataset: [],
      },
      stackedcolumn2d: {
        chart: FusionCharts.curryChartOptions({
          showSum: 1,
          showYAxisValues: 0,
          yAxisLineThickness: 0,
          yAxisLineColor: '#ffffff',
          numDivLines: 0,
          divLineDashed: 0,
          divLineColor: '#ffffff',
          maxColWidth: 25,
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        }),
        categories: [{ category: [] }],
        dataset: [],
      },
      scrollstackedcolumn2d: {
        chart: FusionCharts.curryChartOptions({
          scrollHeight: /iphone|ipad|ipod/i.test(navigator.userAgent) ? 10 : 4,
          scrollColor: '#ffffff',
          showSum: 1,
          showYAxisValues: 0,
          yAxisLineThickness: 0,
          yAxisLineColor: '#ffffff',
          numDivLines: 0,
          divLineDashed: 0,
          divLineColor: '#ffffff',
          maxColWidth: 25,
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        }),
        categories: [{ category: [] }],
        dataset: [],
      },
      msstackedcolumn2dlinedy: {
        chart: FusionCharts.curryChartOptions({
          showSum: 1,
          showYAxisValues: 0,
          pYAxisMaxValue: 180,
          sYAxisMaxValue: 500,
          yAxisLineThickness: 0,
          yAxisLineColor: '#ffffff',
          numDivLines: 0,
          divLineDashed: 0,
          divLineColor: '#ffffff',
          maxColWidth: 25,
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        }),
        categories: [{ category: [] }],
        dataset: [],
      },
      scrollmsstackedcolumn2dlinedy: {
        chart: FusionCharts.curryChartOptions({
          scrollHeight: /iphone|ipad|ipod/i.test(navigator.userAgent) ? 10 : 4,
          scrollColor: '#ffffff',
          showSum: 1,
          showYAxisValues: 0,
          pYAxisMaxValue: 180,
          sYAxisMaxValue: 500,
          yAxisLineThickness: 0,
          yAxisLineColor: '#ffffff',
          numDivLines: 0,
          divLineDashed: 0,
          divLineColor: '#ffffff',
          maxColWidth: 25,
          drawCustomLegendIcon: 1,
          legendIconSides: 0,
          plottooltext: "<div class='fusion-tooltip'><table><tr><th>$seriesname-$label</th><td>$value</td></tr></table></div>",
        }),
        categories: [{ category: [] }],
        dataset: [],
      },
    },
  };
});
